### ISSUE TITLE
Ambiguous resolution of settings seeder

### ISSUE THREAD

**Issue by gotrecillo** [Laravel-Backpack/Settings#51] opened 2017-10-07 16:00 UTC
After
```
php artisan vendor:publish --provider="Backpack\Settings\SettingsServiceProvider"
```
I am getting this error in composer.

```
Warning: Ambiguous class resolution, "Backpack\Settings\database\seeds\SettingsTableSeeder" was found in both "/home/gotre/Projects/backpackgenerator/demo/vendor/backpack/settings/src/database/seeds/SettingsTableSeeder.php" and "/home/gotre/Projects/backpackgenerator/demo/database/seeds/SettingsTableSeeder.php", the first will be used.
```

What about removing the namespace in the seeder published so there is no conflict ?

**Comment by martinjoiner** [comment] 2018-02-28 10:49
I too got this error and deleted my unused app version of the seeder. 

But when trying to understand it I have become confused as to how the SettingsTableSeeder.php in the package gets invoked. 

SettingsServiceProvider.php (Lines 49-50) contains:

    // publish the migrations and seeds
    $this->publishes([__DIR__.'/database/migrations/' => database_path('migrations')], 'migrations');

Which explains how the `migrations` are discovered, but the `seeds` folder is a sibling of migrations and not explicitly referenced in the server provider. 

I am using Laravel 5.6, is this possibly a bug caused by the auto-discovery feature added in 5.6?

**Comment by tabacitu** [comment] 2018-03-13 10:32
Hi guys,

In the Settings installation, developers are _not_ instructed to publish the seeds. Only to run them from the package. I personally think this is the way the installation _should_ be, since the seeds aren't exactly necessary. They're just some demo entries, so you can get started. So no need to copy them in your project, so that they're run on staging/production.

Wouldn't you agree?

Thanks, cheers!

**Comment by tabacitu** [comment] 2018-03-13 11:42
I'll close the issue for now. Reopen or reply if you think I'm wrong to do so. I make mistakes all the time.

Cheers!

**Closed by tabacitu** 2018-03-13 11:42 UTC
Labels: bug

**Comment by martinjoiner** [comment] 2018-03-13 12:03
Just to clarify, I have not published the seeder in my application. The version in the composer library just gets discovered and run somehow! I do not know enough about Laravel 5.6 to know how it's managing to run. I am guessing from your response this is not intended behaviour.
