### ISSUE TITLE
PHP 7.4 compatibility

### ISSUE THREAD

**Issue by ikkebra** [Laravel-Backpack/Settings#95] opened 2020-02-13 15:02 UTC
# Bug report

It does not appear to be compatible with PHP 7.4

### What I did:
I upgraded to PHP 7.4 and then the Settings page does not finish loading and times out.

### What I've already tried to fix it:
I downgraded back to PHP 7.3 and it works again.

### Backpack, Laravel, PHP, DB version:
backpack/crud 4.0.40
laravel v6.15.1
php 7.4.2
MariaDB 10.3.22

**Comment by tabacitu** [comment] 2020-02-16 08:26
Hi @ikkebra ,

That's odd. I just tried it with:

```php
### PHP VERSION:
PHP 7.4.2 (cli) (built: Jan 22 2020 06:30:58) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.2, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
laravel/framework                        v6.13.1            The Laravel Framework.

### BACKPACK VERSION:
backpack/backupmanager                   2.0.3              Admin interface for managing backups in Backpack, on Laravel 5.2+
backpack/crud                            4.0.37             Quickly build an admin interfaces using Laravel 6, CoreUI, Boostrap 4 and jQuery.
backpack/generators                      2.0.6              Generate files for laravel projects
backpack/logmanager                      3.0.3              An interface to preview, download and delete Laravel log files.
backpack/menucrud                        2.0.2              An admin panel for menu items, using Backpack\CRUD on Laravel 6.
backpack/newscrud                        3.0.1              An admin panel for news with categories and tags, using Backpack\CRUD on Laravel 5.
backpack/pagemanager                     2.0.5              Create admin panels for presentation websites on Laravel, using page templates and Backpack\CRUD.
backpack/permissionmanager               5.0.6              Users and permissions management interface for Laravel 5 using Backpack CRUD.
backpack/settings                        3.0.2              Application settings interface for Laravel 5 using Backpack CRUD.
digitallyhappy/toggle-field-for-backpack 1.0.2              Easily toggle boolean attributes with a new field type.
```

And it worked fine for me:
![Screenshot 2020-02-16 at 10 23 41](https://user-images.githubusercontent.com/1032474/74601382-74a53a00-50a6-11ea-89de-d7f20acb4d7b.png)

I've also added PHP 7.4 to TravisCI to test for any issues - PR here https://github.com/Laravel-Backpack/Settings/pull/96 - and it looks ok, this package should work fine on PHP 7.4.

I'll close the issue for now since I wasn't able to reproduce it. But hopefully more people will post here, if they encounter the same problem, and we'll arrive to a solution.

Cheers!

**Closed** 2020-02-16 08:26 UTC
Labels: triage
